const utilities = {
	randomInteger: (minimum, maximum) =>
		Math.floor (Math.random () * (maximum - minimum + 1)) + minimum,
	
	randomElement: array =>
		array [utilities.randomInteger (0, array.length - 1)],
	
	simplifyGreek: text =>
		text.normalize ("NFD")
			.replaceAll (/\p{Diacritic}/gu, "")
			.replaceAll ("ς", "σ")
			.replaceAll ("⸂", "")
			.replaceAll ("⸃", "")
			.toLowerCase ()
			.trim (),
	
	englishToGreek: text =>
		text.replaceAll ("a", "α")
			.replaceAll ("A", "Α")
			.replaceAll ("b", "β")
			.replaceAll ("B", "Β")
			.replaceAll ("c", "ψ")
			.replaceAll ("C", "Ψ")
			.replaceAll ("d", "δ")
			.replaceAll ("D", "Δ")
			.replaceAll ("e", "ε")
			.replaceAll ("E", "Ε")
			.replaceAll ("f", "φ")
			.replaceAll ("F", "Φ")
			.replaceAll ("g", "γ")
			.replaceAll ("G", "Γ")
			.replaceAll ("h", "η")
			.replaceAll ("H", "Η")
			.replaceAll ("i", "ι")
			.replaceAll ("I", "Ι")
			.replaceAll ("j", "ξ")
			.replaceAll ("J", "Ξ")
			.replaceAll ("k", "κ")
			.replaceAll ("K", "Κ")
			.replaceAll ("l", "λ")
			.replaceAll ("L", "Λ")
			.replaceAll ("m", "μ")
			.replaceAll ("M", "Μ")
			.replaceAll ("n", "ν")
			.replaceAll ("N", "Ν")
			.replaceAll ("o", "ο")
			.replaceAll ("O", "Ο")
			.replaceAll ("p", "π")
			.replaceAll ("P", "Π")
			.replaceAll ("r", "ρ")
			.replaceAll ("R", "Ρ")
			.replaceAll ("s", "σ")
			.replaceAll ("S", "Σ")
			.replaceAll ("t", "τ")
			.replaceAll ("T", "Τ")
			.replaceAll ("u", "θ")
			.replaceAll ("U", "Θ")
			.replaceAll ("v", "ω")
			.replaceAll ("V", "Ω")
			.replaceAll ("w", "ς")
			.replaceAll ("W", "Σ")
			.replaceAll ("x", "χ")
			.replaceAll ("X", "Χ")
			.replaceAll ("y", "υ")
			.replaceAll ("Y", "Υ")
			.replaceAll ("z", "ζ")
			.replaceAll ("Z", "Ζ")
};